version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: nikola_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Nikola
    ports:
      - "5432:5432"
    volumes:
      - nikoladata:/var/lib/postgresql/data

volumes:
  nikoladata: